#!/bin/bash
# 平台 env vars 清理 snippet —— 在新 Hermes 启动脚本顶部使用
# 用途：防止新 Hermes 误读旧 ~/.hermes/.env 残留的平台 token

unset FEISHU_APP_ID FEISHU_APP_SECRET FEISHU_DOMAIN FEISHU_CONNECTION_MODE
unset FEISHU_ALLOW_ALL_USERS FEISHU_ALLOWED_USERS FEISHU_ENCRYPT_KEY
unset FEISHU_VERIFICATION_TOKEN FEISHU_BOT_OPEN_ID FEISHU_BOT_USER_ID
unset FEISHU_BOT_NAME FEISHU_GROUP_POLICY FEISHU_WEBHOOK_HOST FEISHU_WEBHOOK_PORT
unset FEISHU_WEBHOOK_PATH FEISHU_REQUIRE_MENTION FEISHU_REACTIONS
unset WEIXIN_ACCOUNT_ID WEIXIN_TOKEN WEIXIN_BASE_URL WEIXIN_CDN_BASE_URL
unset WEIXIN_DM_POLICY WEIXIN_GROUP_POLICY WEIXIN_ALLOWED_USERS
unset WEIXIN_ALLOW_ALL_USERS WEIXIN_GROUP_ALLOWED_USERS WEIXIN_HOME_CHANNEL
unset WEIXIN_SEND_CHUNK_DELAY_SECONDS WEIXIN_SEND_CHUNK_RETRIES
unset WEIXIN_SEND_CHUNK_RETRY_DELAY_SECONDS
unset TELEGRAM_BOT_TOKEN TELEGRAM_ALLOWED_USERS
unset DISCORD_BOT_TOKEN DISCORD_ALLOWED_USERS
unset SLACK_BOT_TOKEN SLACK_ALLOWED_USERS
unset GATEWAY_ALLOW_ALL_USERS
unset HERMES_SESSION_PLATFORM HERMES_SESSION_KEY

# 同时清理新 .env（必须做，光 unset 不够，hermes 会重新读）
# 在新 home 创建 .env 时执行：
#   grep -viE "^(FEISHU|WEIXIN|TELEGRAM|DISCORD|SLACK|GATEWAY_ALLOW_ALL_USERS)" \
#     /home/zcxx/.hermes/.env > /新home/.hermes/.env
